language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

env:
  - COMPOSER_UPDATE=
  - COMPOSER_UPDATE=--prefer-lowest

script:
  - composer update $COMPOSER_UPDATE -n
  - vendor/bin/php-cs-fixer fix --dry-run -v
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then bash <(curl -s https://codecov.io/bash); fi
